### ISSUE TITLE
[Bug]: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

### ISSUE THREAD

**Issue by levi-beers** [jiten14/jitone-ai#2]
### What happened?

Just following example in github instructions gives me:

OpenAI\ Exceptions\ ErrorException
PHP 8.3.9
Laravel 11.23.5

This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

### How to reproduce the bug

Follow installation instructions with latest Laravel

### Package Version

0.1.0

### PHP Version

8.3.9

### Laravel Version

11.23.5

### Which operating systems does with happen with?

macOS

**Comment by jiten14** [comment]
Hi levi-beers,

Thanks for bringing this up!

We use the [openai-php/laravel](https://github.com/openai-php/client) package to communicate with the OpenAI API, so if you're seeing this error, it's likely due to a mismatch between the model and the API endpoint being used. The v1/completions endpoint requires a completions model, while chat models (like gpt-3.5-turbo or gpt-4) should be used with the v1/chat/completions endpoint instead.

The default config file is correctly set up to use the right endpoint. However, if you're passing a custom model through options, please ensure you are using the correct API endpoint as outlined in the [openai-php/client documentation](https://github.com/openai-php/client).

We are also working to support more models and multiple endpoints (through user options) to provide greater flexibility.

Feel free to reach out if you have any more questions!

Best,
Jitendriya
